export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";
export const FETCH_PHOTOS_ERROR = "FETCH_PHOTOS_ERROR";

export const ADD_PHOTO_ERROR = "ADD_PHOTO_ERROR";

export const FETCH_USER_PHOTOS_SUCCESS = "FETCH_USER_PHOTOS_SUCCESS";
export const FETCH_USER_PHOTOS_ERROR = "FETCH_USER_PHOTOS_ERROR";

export const DELETE_PHOTO_ERROR = "DELETE_PHOTO_ERROR";